### ISSUE TITLE
Text is difficult to read when using Visual Studio "Blue" theme

### ISSUE THREAD

**Issue by JeffJacobson** [Microsoft/WhackWhackTerminal#32]
When Visual Studio's theme is set to *Blue* or *Blue (extra contrast)*, the text in the Terminal Window is difficult to read (e.g., yellow text on white background).
![2017-10-10 10_02_53-trafficptrdotnet - microsoft visual studio](https://user-images.githubusercontent.com/713754/31399822-6b07e08c-ada2-11e7-99c1-21f339a717dc.png)

Isn't *Blue* the default theme of Visual Studio? It doesn't make a good first impression when the first thing I notice after installing this extension is that it's difficult to read.

For now I'll just switch to the *Dark* theme (since that's easier than editing the Whack Whack Terminal css file in the user settings).

**Comment by dgriffen** [comment]
I've been trying to determine the best way to fix this issue. Since if I fix the colors in the blue and light themes there will probably be unreadable colors in the _Dark_ theme. I could build in a color set for all three themes, but the issue there is that users can install their own themes which my terminal would be unable to deal with.

In the meantime, if you do wish to use the _Blue_ theme and you don't mind the terminal being black, you can use this as your css file:
```css
.terminal {
    color: white;
}

.terminal .xterm-viewport {
    background-color: black;
}

.terminal .xterm-color-15 {
    color: white;
}

.terminal:not(.focus) .terminal-cursor {
    outline-color: transparent;
    border-bottom: 1px solid white;
}

.terminal.focus:not(.xterm-cursor-style-underline):not(.xterm-cursor-style-bar) .terminal-cursor {
    color: black;
    background-color: white;
}
```
